package main.java.basic;

public enum  Action {
    STARTING_TRANSPORTATION,
    COMPLETION_TRANSPORTATION,
    ABORTING_TRANSPORTATION,
    MOVING_ELEVATOR,
    BOADING_OF_PASSENGER,
    DEBOADING_OF_PASSENGER,
    VALID_TRANSPORTATION
}
