package main.java.basic;

public enum  Action {
    STARTING_TRANSPORTATION,
    COMPLETION_TRANSPORTATION,
    ABORTING_TRANSPORTATION,
    MOVING_ELEVATOR,
    BOARDING_OF_PASSENGER,
    DEBOARDING_OF_PASSENGER,
    VALID_TRANSPORTATION
}
